cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'
tap 'grammarly/tap'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'heroku'
brew 'elixir'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'nvm'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'scriptcs'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'alfred'
cask 'dropbox'
cask 'google-chrome'
cask 'grammarly'
cask 'handbrake'
cask 'mapbox-studio'
cask 'lastpass'
cask 'seashore'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'transmission'
cask 'typora'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'visual-studio-code'
